model:
    arch: Single_agent
    shuffle_features: None
    agent_num: 6
    enc_backbone: resnet_encoder
    dec_backbone: simple_decoder
    feat_squeezer: -1
    feat_channel: 512
    multiple_output: True
data:
    dataset: airsim
    train_split: train
    val_split: val
    test_split: test
    img_rows: 512
    img_cols: 512
    path: dataset/airsim-mrms-data
    noisy_type: None 
    target_view: '6agent'  
training:
    train_iters: 12
    batch_size: 2
    val_interval: 6
    n_workers: 4
    print_interval: 2
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None
